name: Deploy Demo Website

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'demo/**'

jobs:
  main-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Step Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run bootstrap

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website
          GIT_CONFIG_NAME: pengxiaotian
          GIT_CONFIG_EMAIL: 673923162@qq.com
          COMMIT_MESSAGE: website deploy

  sync:
    needs: main-deploy
    runs-on: ubuntu-latest

    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        source-repo: "git@github.com:pengxiaotian/datav-vue.git"
        destination-repo: "git@gitee.com:pengxiaotian/datav-vue.git"
